framework:
    cache:
        pools:
            doctrine.result_cache_pool:
                adapter: cache.adapter.memcached
                provider: doctrine_memcached_provider
            doctrine.system_cache_pool:
                adapter: cache.adapter.memcached
                provider: doctrine_memcached_provider
        app: cache.adapter.redis
        default_redis_provider: '%env(REDIS_DSN)%'
