before_script:
  - eval $(ssh-agent -s)
  - ssh-add <(echo "$SSH_PRIVATE_KEY" | base64 -d)
  - mkdir -p ~/.ssh
  - echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config

deploy_server1:
  stage: deploy
  environment:
    name: server1
    url: $SERVER1
  script:
    - ssh $SSH_USER@$SERVER1 "sudo rm -rf /var/www/demo &&
      cd /var/www &&
      git clone https://github.com/otusteamedu/symfony-deploy-2025-08.git demo &&
      sudo chown www-data:www-data demo -R &&
      cd demo &&
      sh ./deploy.sh $SERVER1 $DATABASE_HOST $DATABASE_USER $DATABASE_PASSWORD $DATABASE_NAME $RABBITMQ_HOST $RABBITMQ_USER $RABBITMQ_PASSWORD"
  only:
    - main