before_script:
  - eval $(ssh-agent -s)
  - echo $SSH_PRIVATE_KEY | base64 -d |tr -d '\r' | ssh-add -
  - mkdir -p ~/.ssh
  - echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
  - export DIR=$(date +%Y%m%d_%H%M%S)

deploy_server1:
  stage: deploy
  environment:
    name: server1
    url: $SERVER1
  script:
    - ssh $SSH_USER@$SERVER1 "sudo docker compose down --remove-orphans && cd /app &&
      git clone https://github.com/otusteamedu/symfony-deploy-2025-08.git $DIR &&
      sudo chown www-data:www-data $DIR -R &&
      cd $DIR &&
      bash ./deploy.sh $SERVER1 $DATABASE_HOST $DATABASE_USER $DATABASE_PASSWORD $DATABASE_NAME $RABBITMQ_HOST $RABBITMQ_USER $RABBITMQ_PASSWORD &&
      cd .. &&
      ( [ ! -d /app/current ] || mv -Tf /app/current /app/previous ) &&
      ln -s /app/$DIR /app/current"
  only:
    - main